name: Conan
on:
  pull_request:
  push:
  release:
    types:
      - published

jobs:
  build-cmake:
    strategy:
      matrix:
        include:
          - os: 'ubuntu-latest'
            branch: 'current'
          - os: 'windows-latest'
            branch: 'current'
          - os: 'macos-latest'
            branch: 'current'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 'Install python dependencies'
        run: |
          python -m pip install -r requirements.txt
          python -m pip install conan
      - name: 'Download pdfium sources'
        run: |
          python download_pdfium.py --branch "${{ matrix.branch }}" --destination "pdfium"
      - name: 'Initialize conan'
        run: |
          conan config init
      - name: 'Configure, build and install static pdfium'
        run: |
          conan create . pdfium/${{ matrix.branch }}@ -o pdfium:shared=False
      - name: 'Configure, build and install shared pdfium'
        run: |
          conan create . pdfium/${{ matrix.branch }}@ -o pdfium:shared=True
