name: Conan
on:
  pull_request:
  push:
  release:
    types:
      - published
  schedule:
    - cron: '0 0 1,15 * *'  # Run approximately every 2 weeks

jobs:
  calculate-matrix:
    runs-on: '${{ matrix.os }}'
    outputs:
      matrix: ${{ steps.calc-build-matrix.outputs.matrix }}
    steps:
      - name: 'Calculate build matrix'
        id: calc-build-matrix
        with:
          entrypoint: python
        run: |
          import itertools
          import json
          os_list = ["ubuntu-latest", "windows-latest", "macos-latest"]
          branch_list = ["current"]
          if "${{ github.event_name }}" != "release":
            branch_list.append("master")
          matrix = [{"os": os, "branch": branch} for os, branch in itertools.product(os_list, branch_list)]
          print("::set-output name=matrix::{}".format(json.dumps(matrix)))
  build-conan:
    needs: 'calculate-matrix'
    strategy:
      matrix: ${{ fromJSON(needs.calculate-matrix.outputs.matrix) }}
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 'Install python dependencies'
        run: |
          python -m pip install -r requirements.txt
      - name: 'Install conan'
        run: |
          python -m pip install conan
      - name: 'Download pdfium sources'
        run: |
          python download_pdfium.py --branch "${{ matrix.branch }}" --destination "pdfium"
      - name: 'Initialize conan'
        run: |
          conan config init
      - name: 'Configure, build and install static pdfium'
        run: |
          conan create . pdfium/${{ matrix.branch }}@ -o pdfium:shared=False
      - name: 'Configure, build and install shared pdfium'
        run: |
          conan create . pdfium/${{ matrix.branch }}@ -o pdfium:shared=True
