name: CI
on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build-cmake:
    strategy:
      matrix:
        include:
          - branch: 'current'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: 'Install python dependencies'
        run: |
          python -m pip install -r requirements.txt
      - name: 'Download pdfium sources'
        run: |
          python download_pdfium.py --branch "${{ matrix.branch }}" --destination "pdfium"
      - name: 'Download Ubuntu packages'
        run: |
          sudo apt-get install libfreetype-dev libicu-dev libjpeg-dev libopenjp2-7-dev libpng-dev libtiff-dev zlib1g-dev
      - name: 'Configure, build and install static pdfium'
        run: |
          cmake -S cmake -B build_static -DPDFIUM_ROOT="${{ github.workspace }}/pdfium" -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=staticprefix
          cmake --build build_static --parallel
          cmake --build build_static --target install
      - name: 'Configure, build and install shared pdfium'
        run: |
          cmake -S cmake -B build_shared -DPDFIUM_ROOT="${{ github.workspace }}/pdfium" -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=sharedprefix
          cmake --build build_shared --parallel
          cmake --build build_shared --target install
